* Задача
Обучите классификатор, предсказывающий категорию объявления на Авито по его заголовку, описанию и цене. Метрика для оценки качества -- accuracy. Необходимо предоставить прокомментированный код (желательно на Python 2.x или 3.x, можно в Jupiter Notebook) для всех этапов решения задачи и результат скоринга файла test.csv с помощью предложенного классификатора (csv-файл с двумя столбцами: item_id, category_id).

Категории имеют иерархическую структуру, описанную в файле сategory.csv. Посчитайте также accuracy вашей модели на каждом уровне иерархии.

Для решения задачи можно использовать любые внешние модели, но не внешние данные. В случае сомнений по поводу возможности использования чего-либо напишите нам.

[[https://start.avito.ru/][форма подачи заявки на стажировку]]
** Данные
[[https://drive.google.com/drive/folders/1PzMQfrDTKmMbgHr0mJWMDfB3X9ZHsIxm?fbclid=IwAR1tGlzZVKwXIbNpt3tpjd4CuYPYN6Rk8bd2waYhmpc2WwYQZiZTVoNlPd0][Ссылка на данные]]

** Решение 

** Оценка качества решения
*** Accuracy по каждому уровню иерархии
[{'Аудио и видео': 0.943,
  'Билеты и путешествия': 0.991,
  'Бытовая техника': 0.961,
  'Велосипеды': 0.939,
  'Игры, приставки и программы': 0.932,
  'Книги и журналы': 0.839,
  'Коллекционирование': 0.795,
  'Красота и здоровье': 0.894,
  'Мебель и интерьер': 0.79,
  'Музыкальные инструменты': 0.905,
  'Настольные компьютеры': 0.952,
  'Ноутбуки': 0.952,
  'Одежда, обувь, аксессуары': 0.843,
  'Охота и рыбалка': 0.877,
  'Планшеты и электронные книги': 0.937,
  'Посуда и товары для кухни': 0.879,
  'Растения': 0.94,
  'Ремонт и строительство': 0.902,
  'Спорт и отдых': 0.806,
  'Телефоны': 0.896,
  'Товары для детей и игрушки': 0.834,
  'Товары для компьютера': 0.951,
  'Часы и украшения': 0.947},
 {'Nokia': 0.917,
  'Samsung': 0.892,
  'Sony': 0.938,
  'iPhone': 0.925,
  'Аксессуары': 0.803,
  'Акустика, колонки, сабвуферы': 0.934,
  'Гитары и другие струнные': 0.931,
  'Двери': 0.959,
  'Детская мебель': 0.729,
  'Детские коляски': 0.921,
  'Для дома': 0.975,
  'Для кухни': 0.948,
  'Для студии и концертов': 0.878,
  'Другие марки': 0.796,
  'Другое': 0.541,
  'Женская одежда': 0.877,
  'Запчасти и аксессуары': 0.939,
  'Зимние виды спорта': 0.929,
  'Игровые приставки': 0.937,
  'Игрушки': 0.784,
  'Игры для приставок': 0.928,
  'Инструменты': 0.898,
  'Книги': 0.829,
  'Кровати, диваны и кресла': 0.828,
  'Монеты': 0.968,
  'Мониторы': 0.952,
  'Освещение': 0.952,
  'Планшеты': 0.937,
  'Посуда': 0.879,
  'Предметы интерьера, искусство': 0.62,
  'Приборы и аксессуары': 0.894,
  'Путешествия': 0.991,
  'Сантехника и сауна': 0.892,
  'Сетевое оборудование': 0.949,
  'Столы и стулья': 0.921,
  'Стройматериалы': 0.865,
  'Текстиль и ковры': 0.922,
  'Телевизоры и проекторы': 0.953,
  'Товары для кормления': 0.896,
  'Учебная литература': 0.85,
  'Фитнес и тренажёры': 0.895,
  'Часы': 0.945,
  'Шкафы и комоды': 0.872,
  'Ювелирные изделия': 0.951},
 {'Верхняя одежда': 0.921,
  'Другое': 0.652,
  'Мелкая кухонная техника': 0.948,
  'Обувь': 0.956,
  'Платья и юбки': 0.954,
  'Стиральные машины': 0.975,
  'Чехлы и плёнки': 0.911}]
*** Accuracy без разделния на уровни иерархии
mean accuracy
0.8750185185185186
----------
accuracy by categories

0: 0.918
1: 0.947
2: 0.884
3: 0.926
4: 0.914
5: 0.955
6: 0.854
7: 0.959
8: 0.934
9: 0.869
10: 0.896
11: 0.942
12: 0.921
13: 0.953
14: 0.967
15: 0.849
16: 0.843
17: 0.864
18: 0.814
19: 0.626
20: 0.841
21: 0.907
22: 0.901
23: 0.504
24: 0.957
25: 0.961
26: 0.99
27: 0.884
28: 0.936
29: 0.959
30: 0.79
31: 0.712
32: 0.908
33: 0.888
34: 0.748
35: 0.945
36: 0.932
37: 0.89
38: 0.686
39: 0.932
40: 0.954
41: 0.854
42: 0.864
43: 0.841
44: 0.609
45: 0.964
46: 0.889
47: 0.682
48: 0.994
49: 0.869
50: 0.953
51: 0.856
52: 0.871
53: 0.945

